sudo: required
services: docker
language: bash
branches:
  only:
  - master
before_script:
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
script:
- "./build.sh"
after_success:
- "./push.sh"
notifications:
  slack:
    rooms:
      secure: gxwlPAC81A26MpRXBgYlh4FCckPdQq1HtHsfcBk/P0E/7wFztkjro2aemZHWnw3vBHDDbmWSKl6ggZ56tBaN2lN1WUBehN7TocMI+/u2prPr0aw9rLbQeZhDwYVq41aqWhOKNeRp9NQXCJ7SFsJyJU9BscW5uc2SWyPapmC0ZHXI1i3SYppx7W4T2S3gBnc31L40RyaZ5aGleJHmHK3ZYhk6krfT1EQs8u6+b3NJoTWniikp6QyqD/r73b0cf1bVNKlMEMBIVOjxYLxREwR0ltnfs4CVDLDzOSCEKTrbJvY20hrHdCM77cGuL7PJs2xHjSkxG2ikTyCyzHMItvNe7gbXFr/bDodW8+VRP2z0QJfnBuzrt0MiEB9eUvlm/bGRCc5M3gtjlUsD5d6S3lekRoVZshAzsVGA/5kDvcPhzWLzw0flAHWL2E/ucfhBD5fe2ji1cIk3Sp4nzANqFxNggy8HdYIBbffpXpwl9M/NO5XkIfyBrgODfjryLLa5gCBwDlk7zW7ju1Z5oE19z7SChH04cv5jOmE0IVl+qVRfjHrRIgNFfjkSOM5JNxHBTnwKuqg3qmpjq5uxNOtRc2xBd+5BozxI8HGqlHbGdfNC5vDGWdfxF7VoKv9PT0YVMyWTylXdtDEjxBpG/m3JC/h/4Rg6XgAsMKtt/s7/K8XeE9U=
